EventConstants = {
  EVENTS_RECEIVED: "EVENTS_RECEIVED",
  SINGLE_EVENT_RECEIVED: "SINGLE_EVENT_RECEIVED",
  FOLLOWING_EVENTS_RECEIVED: "FOLLOWING_EVENTS_RECEIVED",
  DELETE_EVENT: "DELETE_EVENT"
}

module.exports = EventConstants;
