FilterConstants = {
  UPDATE_LOCATION: "UPDATE_LOCATION",
  UPDATE_PRICE: "UPDATE_PRICE",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  UPDATE_DATE: "UPDATE_DATE",
  UPDATE_TITLE: "UPDATE_TITLE"
};

module.exports = FilterConstants;
