var UserConstants = {
  GET_SINGLE_USER: "GET_SINGLE_USER",
  FOLLOWERS_RECEIVED: "FOLLOWERS_RECEIVED",
  ADD_FOLLOW: "ADD_FOLLOW",
  REMOVE_FOLLOW: "REMOVE_FOLLOW",
  EDIT_PROFILE: "EDIT_PROFILE",
  FOLLOWINGS_RECEIVED: "FOLLOWINGS_RECEIVED",
  COMMENTS_RECEIVED: "COMMENTS_RECEIVED",
  ADD_COMMENT: "ADD_COMMENT",
  REMOVE_COMMENT: "REMOVE_COMMENT"
};

module.exports = UserConstants;
