json.url @user.url
json.id @user.id
json.background_url @user.background_url
json.first_name @user.first_name
json.last_name @user.last_name
json.host_name @user.host_name
json.description @user.description
json.email @user.email
json.events @user.events
